FROM fedora:28

MAINTAINER Bernhard Bermeitinger <bernhard.bermeitinger@gmail.com>

RUN dnf upgrade --assumeyes \
	&& dnf install --assumeyes \
		texlive-scheme-basic \
		latexmk


RUN rm -r /var/cache/dnf; \
	mkdir /.cache/ && chmod 777 /.cache && \
	mkdir /.texlive2017 && chmod 777 /.texlive2017

WORKDIR /data
VOLUME ["/data"]
