FROM bermeitingerb/texlive:base

COPY install.profile /install-tl/install.profile

RUN wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz && \
	tar xfa install-tl-unx.tar.gz -C /install-tl --strip-components=1 && \
	/install-tl/install-tl -profile /install-tl/install.profile && \
	rm -rf \
		/install-tl-unx.tar.gz \
		/install-tl \
		/var/cache/dnf

ENV PATH="/usr/local/texlive/bin/x86_64-linux:${PATH}"
