FROM fedora:32

LABEL maintainer="Bernhard Bermeitinger <bernhard.bermeitinger@gmail.com>"

RUN dnf upgrade -y && \
    dnf install -y \
        libnsl \
        wget \
        perl \
        fontconfig \
        ghostscript \
        libxcrypt-compat && \
    dnf clean all && \
    rm -rf /var/cache/dnf

ENV PATH="/usr/local/texlive/bin/x86_64-linux:${PATH}"

WORKDIR /data
VOLUME ["/data"]
