FROM bermeitingerb/texlive:full

MAINTAINER Bernhard Bermeitinger <bernhard.bermeitinger@gmail.com>

RUN dnf upgrade --assumeyes && \
    rm -r /var/cache/dnf && \
    tlmgr update --self && \
    tlmgr update --all
