FROM fedora:32

LABEL maintainer="Bernhard Bermeitinger <bernhard.bermeitinger@gmail.com>"

RUN dnf upgrade -y && \
    dnf install -y \
        libnsl \
        wget \
        perl \
        fontconfig \
        ghostscript \
        libxcrypt-compat

WORKDIR /data
VOLUME ["/data"]
