FROM bermeitingerb/texlive:latest

LABEL maintainer="Bernhard Bermeitinger <bernhard.bermeitinger@gmail.com>"

RUN dnf upgrade --assumeyes && \
    rm -r /var/cache/dnf && \
    tlmgr update --self && \
    tlmgr update --all
