FROM fedora:27

MAINTAINER Bernhard Bermeitinger <bernhard.bermeitinger@gmail.com>

RUN dnf upgrade --assumeyes

RUN dnf install --assumeyes \
	texlive-scheme-basic \
	latexmk


RUN rm -r /var/cache/dnf; \
	mkdir /.cache/ && chmod 777 /.cache

WORKDIR /data
VOLUME ["/data"]